name: Web Scraping Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # 每天 05:00 執行

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Set up environment variable for API_KEY
      run: echo "YOUTUBE_API=${{ secrets.YOUTUBE_API }}" >> $GITHUB_ENV  # 將 Secret 設為環境變數

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run static.py scraper
      run: |
        python static.py

    - name: Run api.py scraper
      run: |
        python api.py

    - name: Commit Data Back To GitHub Repo
      run: |
        git config --global user.name "crawler-bot"
        git config --global user.email "crawler-bot@gmail.com"
        git add . && git commit -m "daily crawl" || echo "nothing to commit"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: |
        rm -rf output_directory
